### ISSUE TITLE
Having an option to pick a custom slash command

### ISSUE THREAD

**Issue by libussa** [wreiske/Rocket.Chat.App-Giphy#2]
Like the title says, it would be nice to pick a custom chat command to replace the de fault /giphy

**Comment by wreiske** [comment]
I'm not sure if it is possible to register a custom slash command after the fact. I may be mistaken. I'll check with Rocket.Chat Apps engine devs on this one and get back to you.

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/54409083-3d225680-46bb-11e9-85ab-998f7410cb66.png)
Looks like this would take some tweaking of the Apps Engine to make this possible. I'm going to close this since it isn't an issue with this app.

Feel free to post your feature request to the Rocket.Chat Apps Engine repo.
https://github.com/RocketChat/Rocket.Chat.Apps-engine

Thanks!
