### ISSUE TITLE
/giphy command comes back

### ISSUE THREAD

**Issue by bigcammy** [wreiske/Rocket.Chat.App-Giphy#4]
After executing a /giphy command and selecting the giphy to apply, the /giphy command I executed goes away, but then if I click away to another direct message or channel and then come back, the /giphy command I executed previously is back in the chat window so I have to manually delete it or backspace it.

**Comment by wreiske** [comment]
This may be an issue with the Rocket.Chat apps engine. I'll send a message to the devs and report back what I find. You might have to open an issue on rocket.chat.

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/54409024-f896bb00-46ba-11e9-9dfa-430d02e7caa0.png)

Looks like it is a known issue. I'm going to close this for now since it is a Rocket.Chat specific issue, not an issue with this Rocket.Chat App. 

Try reporting the issue in the official rocket.chat repository. 
https://github.com/RocketChat/Rocket.Chat/issues

Thanks!
